# Site settings
title: Flama’s CSS StyleGuide
email: contas@flama.me
description: Best practices for using CSS
baseurl: "/css-styleguide"
url: "http://flama.is"
twitter_username: studioflama
github_username:  flama

# Build settings
markdown: kramdown
permalink: /title

# assets:
#   sources:
#     - assets/fonts
#     - assets/javascripts

collections:
  contents:
    output: true
     
navigation:
- text: Flama’s CSS Styleguide
  url: /
- text: Coding Style
  url: /contents/coding-style
- text: Tools
  url: /contents/tools
- text: Class Naming Convention
  url: /contents/class-naming-convention
- text: Stylesheets Folder Architecture
  url: /contents/stylesheets-folder-architecture
- text: Units
  url: /contents/units
- text: Colors
  url: /contents/colors
- text: Typography
  url: /contents/typography
- text: Grid
  url: /contents/grid
- text: Designing for different sized plataforms
  url: /contents/designing-for-different-sized-plataforms
- text: CSS for JavaScript
  url: /contents/css-for-javascript
